name: Build Tauri App
on:
  workflow_call:
jobs:
  Deploy:
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install tools
        uses: asdf-vm/actions/install@v2
      - name: Install dependencies
        run: bun install
      - name: Build Tauri app
        run: bun run tauri build
