name: Build Tauri App
on:
  workflow_call:
jobs:
  Deploy:
    permissions:
      contents: write
    strategy:
      matrix:
        sys:
          { os: ubuntu-20.04, shell: bash },
          { os: windows-latest, shell: msys2 },
          { os: macos-latest, shell: bash }
    defaults:
      run:
        shell: ${{ matrix.sys.shell }} {0}
    runs-on: ${{ matrix.sys.os }}
    steps:
      - name: Setup MSYS2
        if: matrix.sys.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            curl
            git
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install tools
        uses: asdf-vm/actions/install@v2
      - name: Install dependencies
        run: bun install
      - name: Install Ubuntu-specific Dependencies
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Release Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app_v__VERSION__
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
