name: Deploy
run-name: ${{ github.event.head_commit.message }}
on:
  push:
    branches: [main]
  pull_request:
    types:
      -closed
    branches: [main]
jobs:
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.putputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install tools
        uses: asdf-vm/actions/install@v2
      - name: Install dependencies
        run: bun install
      - name: Build website
        run: bun run build
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          path: ./dist
